library(dplyr)
setwd(here::here())
# source https://parisdata.opendatasoft.com/explore/dataset/comptage-velo-donnees-compteurs/information/?disjunctive.id&disjunctive.name&sort=date&dataChart=eyJxdWVyaWVzIjpbeyJjaGFydHMiOlt7InR5cGUiOiJhcmVhc3BsaW5lIiwiZnVuYyI6IkFWRyIsInlBeGlzIjoiY291bnRzIiwic2NpZW50aWZpY0Rpc3BsYXkiOnRydWUsImNvbG9yIjoiI0ZGQ0QwMCJ9XSwieEF4aXMiOiJkYXRlIiwibWF4cG9pbnRzIjoiIiwidGltZXNjYWxlIjoiaG91ciIsInNvcnQiOiIiLCJjb25maWciOnsiZGF0YXNldCI6ImNvbXB0YWdlLXZlbG8tZG9ubmVlcy1jb21wdGV1cnMiLCJvcHRpb25zIjp7ImRpc2p1bmN0aXZlLmlkIjp0cnVlLCJkaXNqdW5jdGl2ZS5uYW1lIjp0cnVlLCJzb3J0IjoiZGF0ZSIsInEudGltZXJhbmdlLmRhdGUiOiJkYXRlOlsyMDE5LTEyLTExVDIzOjAwOjAwWiBUTyAyMDE5LTEyLTE5VDIyOjU5OjU5Wl0ifX19XSwiZGlzcGxheUxlZ2VuZCI6dHJ1ZSwiYWxpZ25Nb250aCI6dHJ1ZSwidGltZXNjYWxlIjoiIn0%3D
# read data with csv2 since sep is ';'
cycling <- readr::read_csv2(file = "paris-strike/data/comptage-velo-donnees-compteurs.csv", )
head(cycling)
